#pragma once
#include "OutputFileParser.h"
#include "OutputData.h"

// BEMTOutputParser class is responsible for parsing the output file generated by the BEMT method.
// It is a little misnamed, since it can handle both Vortex and BEMT output files, but it would be too much work to rename it in the entire hiearchy.
class BEMTOutputParser : public OutputFileParser {
public:
    BEMTOutputParser(const std::wstring& filePath);
    bool parse(OutputData& data) override;

private:
    bool processLine(const std::wstring& line, OutputData& data) override;
    bool inTableSection;
    OutputData::Table currentTable;
};